spring:
  application:
    name: sistema_completo
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_greentech?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Bogota
  jackson:
    time-zone: America/Bogota
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  websocket:
    allowed-origins: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: greentechonesystem@gmail.com
    password: akse nlfy lzun noun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  address: 0.0.0.0
  port: 8080

app:
  frontend:
    url: http://localhost:4200